LimboLand/Controllers/AmigosController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Repository.Repository;

namespace LimboLand.Controllers
{
    [Authorize]
    public class AmigosController : Controller
    {
        private readonly UsuarioRepo _usuarioRepo;
        private readonly PublicacionesRepo _publicacionesRepo;
        private readonly AmigosRepo _amigosRepo;


        public AmigosController(UsuarioRepo usuarioRepo, PublicacionesRepo publicacionesRepo,
            AmigosRepo amigosRepo)
        {
            _usuarioRepo = usuarioRepo;
            _publicacionesRepo = publicacionesRepo;
            _amigosRepo = amigosRepo;

        }
        //Id del Usuario Logueado
        #region IdUser
        public async Task<int> IdUser()
        {
            var usu = await _usuarioRepo.GetUsuarioByName(User.Identity.Name);
            return usu.IdUsuarios;
        }
        #endregion


        //Listado de Amigos
        #region ListaAmigos
        public async Task<IActionResult> ListaAmigos()
        {
            var friends = await _amigosRepo.TraerListaAmigos(await IdUser());
            return View(friends);
        }
        #endregion


        //Buscar Personas
        #region BuscarPersonas
        public async Task<IActionResult> Buscar(string Name)
        {
            var Personas = await _amigosRepo.BuscarPersonas(Name);
            return View(Personas);
        }
        #endregion


        //Agregar Amigos
        #region AgregarAmigos
        public async Task<IActionResult> Agregar(int IdAmigo)
        {
            await _amigosRepo.AgregarAmigos(await IdUser(), IdAmigo);
            return RedirectToAction("ListaAmigos");
        }
        #endregion


        //Eliminar Amigos
        #region EliminarAmigos
        public async Task<IActionResult> EliminarAmigos(int id)
        {
            await _amigosRepo.BorrarAmigos(await IdUser(), id);
            return RedirectToAction("ListaAmigos");
        }
        #endregion

    }
}

LimboLand/Controllers/HomePageController.cs
using System.Threading.Tasks;
using DataBase.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Repository.Repository;

namespace LimboLand.Controllers
{
    [Authorize]
    public class HomePageController : Controller
    {
        private readonly UsuarioRepo _usuarioRepo;
        private readonly PublicacionesRepo _publicacionesRepo;
        private readonly ComentariosRepo _comentariosRepo;


        public HomePageController(UsuarioRepo usuarioRepo, PublicacionesRepo publicacionesRepo,
            ComentariosRepo comentariosRepo)
        {
            _usuarioRepo = usuarioRepo;
            _publicacionesRepo = publicacionesRepo;
            _comentariosRepo = comentariosRepo;

        }

        //Id del Usuario Logueado
        #region IdUser
        public async Task< int> IdUser()
        {
            var usu = await _usuarioRepo.GetUsuarioByName(User.Identity.Name);
            return usu.IdUsuarios;
        }
        #endregion


        //Index del Home Usuario donde se muestran sus publicaciones
        #region HomePage
        public async Task<IActionResult> Index()
        {

            var pubs = await _publicacionesRepo.TraerPubs(await IdUser());
            pubs.Usuario = User.Identity.Name;
            return View(pubs);
        }

        [HttpPost]
        public async Task<IActionResult> Index(PublicacionesViewModel publicacionesViewModel)
        {
            if (ModelState.IsValid)
            {
                await _publicacionesRepo.CrearPubs(publicacionesViewModel);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
        #endregion


        //Comentar Publicaciones
        #region comentar
        [HttpPost]
        public async Task<IActionResult> Comentar(ComentariosViewModel cm)
        {
            await _comentariosRepo.CrearComent(cm);
            if (cm.Manda == 2)
            {
                return RedirectToAction("Index", "HomeAmigos");

            }
            return RedirectToAction("Index");
        }
        #endregion


        //Responder Publicaciones
        #region Responder
        [HttpPost]
        public async Task<IActionResult> Responder(RespuestaViewModel respuesta)
        {
            await _comentariosRepo.CrearRespuesta(respuesta);
            if (respuesta.Manda == 2)
            {
                return RedirectToAction("Index", "HomeAmigos");

            }
            return RedirectToAction("Index");
        }
        #endregion


        //Editar Publicaciones
        #region EditarPub
        public async Task<IActionResult> EditarPub(int id)
        {
            var editar = await _publicacionesRepo.TraerPubById(id);
            return View(editar);
        }

        [HttpPost]
        public async Task<IActionResult> EditarPub(PublicacionesViewModel edit)
        {
            if (ModelState.IsValid)
            {
                await _publicacionesRepo.EditarPubs(edit);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");

        }
        #endregion


        //Eliminar Publicaciones
        #region EliminarPubs
        public async Task<IActionResult> EliminarPub(int id)
        {
            var editar = await _publicacionesRepo.EliminarPub(id);
            return RedirectToAction("Index");
        }
        #endregion

    }
}

LimboLand/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Limbo</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
          crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>

    

</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a asp-area="" asp-controller="HomePage" asp-action="Index" class="navbar-brand">Limbo</a>
        <a asp-area="" asp-controller="HomeAmigos" asp-action="Index">Publicaciones de Amigos</a>
        <a asp-area="" asp-controller="Amigos" asp-action="ListaAmigos">Mis Amigos</a>
        <a asp-area="" asp-controller="Account" asp-action="CerrarSesion">Cerrar Sesion</a>

        <form asp-action="Buscar" asp-controller="Amigos">
            <div class="input-group">
                <input type="search" name="Name" class="form-control" required placeholder="Buscar Nuevos Amigos">
                <div class="input-group-append">
                    <button class="btn btn-outline-primary" type="submit" id="button-addon2">
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        </form>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()

    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>